# Generated by Django 2.1.7 on 2019-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("slackauth", "0003_auto_20190402_1615")]

    operations = [
        migrations.AlterField(
            model_name="slacktoken",
            name="scopes",
            field=models.TextField(blank=True, verbose_name="scopes"),
        )
    ]
