# Generated by Django 2.1.7 on 2019-04-02 17:01

import allauth.socialaccount.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("slackauth", "0004_auto_20190402_1621")]

    operations = [
        migrations.AddField(
            model_name="slacktoken",
            name="extra_data",
            field=allauth.socialaccount.fields.JSONField(default=dict),
        )
    ]
