# Generated by Django 2.1.7 on 2019-04-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackauth', '0006_auto_20190403_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slacktoken',
            unique_together=set(),
        ),
    ]
