# Generated by Django 2.1.7 on 2019-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackauth', '0008_auto_20190403_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slacktoken',
            name='scope',
            field=models.TextField(blank=True, verbose_name='scope'),
        ),
    ]
