# Generated by Django 2.1.7 on 2019-04-03 15:40

import allauth.socialaccount.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('slackauth', '0011_auto_20190403_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackBotToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('extra_data', allauth.socialaccount.fields.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date_created')),
                ('slack_bot_id', models.CharField(max_length=10)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackauth.SlackTeam')),
            ],
        ),
        migrations.CreateModel(
            name='SlackUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('extra_data', allauth.socialaccount.fields.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date_created')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackauth.SlackAccount')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp')),
            ],
            options={
                'verbose_name': 'slack application token',
                'verbose_name_plural': 'slack application tokens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='slackusertoken',
            unique_together={('app', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='slackbottoken',
            unique_together={('app', 'team')},
        ),
    ]
