# Generated by Django 2.1.7 on 2019-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('slackauth', '0015_auto_20190403_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackusertoken',
            old_name='account',
            new_name='slack_account',
        ),
        migrations.AlterUniqueTogether(
            name='slackusertoken',
            unique_together={('app', 'slack_account')},
        ),
    ]
