# Generated by Django 2.2 on 2019-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackauth', '0017_auto_20190404_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackteam',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
