# Generated by Django 2.2 on 2019-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackauth', '0018_auto_20190427_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackaccount',
            name='name',
            field=models.CharField(default='NONAME', max_length=255),
            preserve_default=False,
        ),
    ]
