"""
Django settings for jjalbot project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .production_base import *


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]
