"""
Django settings for jjalbot project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ADMINS = [
    ('Joon', 'joonhyung.shin@kaist.ac.kr'),
]

ALLOWED_HOSTS = [
    'run.kaist.ac.kr',
    'localhost',
    '127.0.0.1',
]


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT')
    }
}

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = '/var/jjalbot/static'

MEDIA_ROOT = '/var/jjalbot/media'


# Remove development setting
SERVE_MEDIA = False
