language: minimal

os:
  - linux

services:
  - docker

script:
  - docker-compose build
  - docker-compose run jjalbot sh check.sh

deploy:
  - provider: script
    script: sh deploy.sh
    on:
      branch: master
