sudo: required
services:
  - docker

script:
  - docker-compose build
  - docker-compose run jjalbot sh startup.sh

deploy:
  - provider: script
    script: fab deploy --branch "$TRAVIS_BRANCH"
    on:
      branch: master
