# Generated by Django 2.1.7 on 2019-03-23 17:41

import allauth.socialaccount.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackAccount",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="socialaccount.SocialAccount",
                    ),
                ),
                ("slack_user_id", models.CharField(max_length=10)),
                ("extra_data", allauth.socialaccount.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SlackTeam",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=21, unique=True)),
                ("verified", models.BooleanField(default=False)),
                ("size", models.IntegerField(default=0)),
                ("max_size", models.IntegerField(default=10000000)),
                ("delete_eta", models.IntegerField(default=3600)),
                ("extra_data", allauth.socialaccount.fields.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="slackaccount",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="slack.SlackTeam"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slackaccount", unique_together={("team", "slack_user_id")}
        ),
    ]
