# Generated by Django 2.2.3 on 2019-07-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slackauth', '0020_copy_slack_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatManualStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.IntegerField(default=0)),
                ('max_entry', models.IntegerField(default=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slackauth.SlackTeam')),
            ],
        ),
        migrations.CreateModel(
            name='ChatManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_re', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('eval_order', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackauth.SlackAccount')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.ChatManualStorage')),
            ],
            options={
                'ordering': ('eval_order',),
            },
        ),
    ]
