# Generated by Django 2.1.7 on 2019-03-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bigemoji", "0010_auto_20190329_1509")]

    operations = [
        migrations.AddField(
            model_name="bigemoji",
            name="alias",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bigemoji.BigEmoji",
            ),
        )
    ]
