# Generated by Django 2.1.7 on 2019-03-30 15:56

import bigemoji.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigemoji', '0011_bigemoji_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigemoji',
            name='image',
            field=models.ImageField(null=True, upload_to=bigemoji.models.team_directory),
        ),
    ]
