# Generated by Django 2.1.7 on 2019-03-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bigemoji", "0014_bigemojistorage_max_entry")]

    operations = [
        migrations.AddField(
            model_name="bigemoji",
            name="storage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bigemoji.BigEmojiStorage",
            ),
        )
    ]
