# Generated by Django 2.1.7 on 2019-04-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigemoji', '0018_auto_20190403_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigemojistorage',
            name='entries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigemojistorage',
            name='occupied',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
