# Generated by Django 2.1.7 on 2019-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigemoji', '0020_bigemoji_storage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigemojistorage',
            name='entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bigemojistorage',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
    ]
