# Generated by Django 2.2.2 on 2019-06-17 17:37

import bigemoji.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigemoji', '0021_auto_20190410_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigemoji',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bigemoji.BigEmoji'),
        ),
        migrations.AlterField(
            model_name='bigemoji',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=bigemoji.models.team_directory),
        ),
    ]
